#!/bin/sh

mkdir -p ../obj/asdf-cache/$@/

if $GNUMAKE -j1 -C $@ build < /dev/null 2>&1 && touch ../obj/asdf-cache/$@/build-passed.test-report ; then
	:
else
	exit $?
fi | tee ../output/building-contrib.$@
