(error "Can't build contribs with ASDF")

(defsystem "sb-manual"
  :serial t
  :components ((:file "package")
               (:file "pax")
               (:file "docstring")
               (:file "markdown" :if-feature :sb-doc)
               (:file "texinfo" :if-feature :sb-doc)
               (:file "manual")
               (:module "doc/"
                :serial t
                :components ((:file "concepts")
                             (:file "sbcl")
                             (:file "support-and-bugs")
                             (:file "intro")
                             (:file "start-stop")
                             (:file "compiler")
                             (:file "debugger")
                             (:file "efficiency")
                             (:file "beyond-ansi")
                             (:file "external-formats")
                             (:file "ffi")
                             (:file "pathnames")
                             (:file "streams")
                             (:file "package-locks")
                             (:file "threading")
                             (:file "timers")
                             (:file "../../sb-bsd-sockets/manual")
                             (:file "profiling")
                             (:file "contrib-modules")
                             (:file "../../sb-aclrepl/manual")
                             (:file "../../sb-concurrency/manual")
                             (:file "../../sb-cover/manual")
                             (:file "../../sb-grovel/manual")
                             (:file "../../sb-introspect/manual")
                             (:file "../../sb-md5/manual")
                             (:file "../../sb-posix/manual")
                             (:file "../../sb-queue/manual")
                             (:file "../../sb-rotate-byte/manual")
                             (:file "../../sb-simd/manual"
                              :if-feature (:or :x86-64 :arm64))
                             (:file "../../sb-simple-streams/manual")
                             (:file "deprecation")))
               (:file "late")))
