(in-package :sb-manual)

(defsection @sbcl-manual (:title "SBCL Manual")
  (@support-and-bugs section)
  (@introduction section)
  (@starting-and-stopping section)
  (@compiler section)
  (@debugger section)
  (@efficiency section)
  (@beyond-the-ansi-standard section)
  (@external-formats section)
  (@foreign-function-interface section)
  (@pathnames section)
  (@streams section)
  (@package-locks section)
  (@threading section)
  (@timers section)
  (@networking section)
  (@profiling section)
  (@contributed-modules section)
  (@deprecation section))
