 <!-- markup for common expressions -->
 <!ENTITY AMOP       "<acronym>AMOP</acronym>">
 <!ENTITY ANSI       "<acronym>ANSI</acronym>">
 <!ENTITY CMUCL      "<application>CMU CL</application>">
 <!ENTITY IEEE       "<acronym>IEEE</acronym>">
 <!ENTITY Python     "<application>Python</application>">
 <!ENTITY SBCL       "<application>SBCL</application>">

 <!-- common expressions I haven't figured out how to mark up -->
 <!-- KLUDGE: There doesn't seem to be any DocBook tag for names of
      programming languages. Typesetting Common Lisp as an
      <application> looks funny. Is there a better way?
      WHN 20000505 -->
 <!ENTITY CommonLisp "Common Lisp">
 <!ENTITY Lisp       "Lisp">

