;;;; Select between tagged or untagged VOPs
;;;;
;;;; This software is part of the SBCL system. See the README file for
;;;; more information.
;;;;
;;;; This software is derived from the CMU CL system, which was
;;;; written at Carnegie Mellon University and released into the
;;;; public domain. The software is in the public domain and is
;;;; provided with absolutely no warranty. See the COPYING and CREDITS
;;;; files for more information.

(in-package "SB-C")

;;; Using a flow graph, separate tagged (source) and untagged (sink)
;;; using min-cut via the Edmonds-Karp algorithm
(defstruct (net (:constructor %make-net ()))
  (table (make-hash-table :test 'eq))
  (head (make-array 16 :element-type '(signed-byte 32) :initial-element -1 :adjustable t :fill-pointer 0)
   :type (vector (signed-byte 32)))
  (to (make-array 32 :element-type '(unsigned-byte 32) :adjustable t :fill-pointer 0)
   :type (vector (unsigned-byte 32)))
  (cap (make-array 32 :element-type '(unsigned-byte 32) :adjustable t :fill-pointer 0)
   :type (vector (unsigned-byte 32)))
  (next (make-array 32 :element-type '(signed-byte 32) :adjustable t :fill-pointer 0)
   :type (vector (signed-byte 32))))

(defun nid-p (net x)
  (gethash x (net-table net)))

(defun nid (net x)
  (or (gethash x (net-table net))
      (setf (gethash x (net-table net))
            (vector-push-extend -1 (net-head net)))))

(defun make-net ()
  (let ((n (%make-net)))
    (nid n :source)
    (nid n :sink)
    n))

(defun add-edge (net u v c)
  (let ((u (nid net u))
        (v (nid net v)))
    (flet ((add (from to cap)
             (vector-push-extend to (net-to net))
             (vector-push-extend cap (net-cap net))
             (vector-push-extend (aref (net-head net) from) (net-next net))
             (setf (aref (net-head net) from) (1- (length (net-to net))))))
      (add u v c)
      (add v u 0))))

(defun min-cut (net)
  (declare (optimize speed))
  (let* ((to (net-to net))
         (cap (net-cap net))
         (next (net-next net))
         (head (net-head net))
         (n (length head))
         (path (make-array n :element-type '(signed-byte 32)))
         (queue (make-array n :element-type '(unsigned-byte 32))))
    (loop
     (fill path -1)
     (setf (aref path 0) -2)
     (let ((qh 0) (qt 1))
       (setf (aref queue 0) 0)
       (loop while (and (< qh qt) (= (aref path 1) -1))
             do (let ((u (aref queue qh)))
                  (incf qh)
                  (loop for e = (aref head u) then (aref next e)
                        while (>= e 0)
                        do (let ((v (aref to e)))
                             (when (and (= (aref path v) -1)
                                        (> (aref cap e) 0))
                               (setf (aref path v) e
                                     (aref queue qt) v)
                               (incf qt)))))))
     (when (= (aref path 1) -1)
       (return (lambda (x)
                 (/= (aref path (nid net x)) -1))))
     (let ((bot (loop for v = 1 then (aref to (logxor e 1))
                      for e = (aref path v)
                      until (= v 0)
                      minimize (aref cap e))))
       (loop for v = 1 then (aref to (logxor e 1))
             for e = (aref path v)
             while (/= v 0)
             do (decf (aref cap e) bot)
                (incf (aref cap (logxor e 1)) bot))))))

(defun tagged-template-results-p (vop-info)
  (loop for costs in (vop-info-result-costs vop-info)
        always (eql (svref costs sb-vm:any-reg-sc-number) 0)))

(defun tagged-template-arg-p (n vop-info)
  (let ((costs (loop with arg-costs = (vop-info-arg-costs vop-info)
                     for i from 0
                     for arg-type in (vop-info-arg-types vop-info)
                     when (= i n)
                     return (car arg-costs)
                     unless (typep arg-type '(cons (eql :constant)))
                     do (pop arg-costs))))
    (aver costs)
    (cond ((not (eql (svref costs sb-vm:any-reg-sc-number) 0))
           (values 0 1))
          ((not (eql (svref costs sb-vm:signed-reg-sc-number) 0))
           (values 1 0))
          (t
           (values 0 0)))))

(defun combination-arg-template-position (arg node)
  (let ((args (combination-args node)))
    (position arg (if (combination-is node '(%%primitive))
                      (cdr args)
                      args))))

(defun select-tagging (component)
  (let ((net (make-net)))
    (do-blocks (block component)
      (do-nodes (node nil block)
        (when (and (combination-p node)
                   (consp (combination-info node)))
          (let (seen)
            (flet ((add-lvar (lvar)
                     (add-edge net lvar node 10)
                     (add-edge net node lvar 10))
                   (read-costs (lvar node)
                     (cond ((constant-lvar-p lvar)
                            (values 0 0))
                           ((combination-p node)
                            (let ((template (combination-info node)))
                              (cond ((atom template)
                                     (if (vop-info-p template)
                                         (tagged-template-arg-p (combination-arg-template-position lvar node)
                                                                (combination-info node))
                                         (values 1 0)))
                                    ((/= (vop-info-related-args (car template)) -1)
                                     (let ((pos (combination-arg-template-position lvar node)))
                                       (if (logbitp pos (vop-info-related-args (car template)))
                                           (values 0 0)
                                           (tagged-template-arg-p pos (car template)))))
                                    (t
                                     ;; Flexible VOP, no costs
                                     (values 0 0)))))
                           (t
                            (values 1 0)))))

              (loop for related fixnum = (vop-info-related-args (car (combination-info node)))
                    then (ash related -1)
                    for arg in (combination-args node)
                    do
                    (unless (or (constant-lvar-p arg)
                                (not (logbitp 0 related)))
                      (add-lvar arg)
                      (let ((tagged 0)
                            (untagged 0))
                        (declare (fixnum tagged untagged))
                        (map-all-uses (lambda (use)
                                        (cond ((combination-p use)
                                               (let ((template (combination-info use)))
                                                 (unless (consp template)
                                                   (if (and (vop-info-p template)
                                                            (not (tagged-template-results-p template)))
                                                       (incf untagged)
                                                       (incf tagged)))))
                                              (t
                                               (incf tagged))))
                                      arg
                                      :var-home
                                      (lambda (var)
                                        (unless (memq var seen)
                                          (push var seen)
                                          (loop for ref in (leaf-refs var)
                                                for lvar = (node-lvar ref)
                                                do (when (and lvar
                                                              (not (constant-lvar-p lvar)))
                                                     (map-all-dests
                                                      (lambda (dest lvar nth-value)
                                                        (declare (ignorable lvar nth-value))
                                                        (multiple-value-bind (tag untag) (read-costs lvar dest)
                                                          (incf tagged tag)
                                                          (incf untagged untag))
                                                        nil)
                                                      ref))))))
                        (when (> tagged 0)
                          (add-edge net :source arg (* tagged 10)))
                        (when (> untagged 0)
                          (add-edge net arg :sink (* untagged 10))))))
              (let ((tagged 0)
                    (untagged 0)
                    (result (node-lvar node)))
                (declare (fixnum tagged untagged))
                (add-lvar result)
                (map-all-dests
                 (lambda (dest lvar nth-value)
                   (declare (ignorable lvar nth-value))
                   (multiple-value-bind (tag untag) (read-costs lvar dest)
                     (incf tagged tag)
                     (incf untagged untag))
                   nil)
                 node)
                (when (> tagged 0)
                  (add-edge net :source result (* tagged 10)))
                (when (> untagged 0)
                  (add-edge net result :sink (* untagged 10)))))))))
    (when (> (length (net-to net)) 0)
      (let ((tagged-p (min-cut net)))
        (loop for node being the hash-key of (net-table net)
              do
              (when (combination-p node)
                (let ((info (combination-info node)))
                  (aver (listp info))
                  (setf (combination-info node)
                        (if (funcall tagged-p node)
                            (first info)
                            (second info))))))))))
