@node function index
@comment  node-name,  next,  previous,  up
@appendix Function and Macro Index

@printindex ff

@node variable index
@comment  node-name,  next,  previous,  up
@appendix Variable and Constant Index

@printindex vv

@node type index
@comment  node-name,  next,  previous,  up
@appendix Type Index

@printindex tt

@node declaration index
@comment  node-name,  next,  previous,  up
@appendix Declaration Index

@printindex dd

@node colophon
@comment  node-name,  next,  previous,  up
@unnumbered Colophon

This manual is maintained as part of the @ref{sb manual} contrib.
@code{SB-MANUAL} can generate Texinfo, which is in turn converted into
other formats (e.g. HTML or pdf). If you're @emph{reading} this manual
in one of these, that's fine, but if you want to @emph{modify} this
manual, you are strongly advised to seek the sources (most live under
@file{contrib/sb-manual/doc/}) and submit a patch.

@ifinfo
When viewing Info in Emacs, the reader inserts superfluous ``see''
words before internal links. Use @code{(setq Info-hide-note-references
'hide)} to prevent this.
@end ifinfo
