@node Contributed Modules
@comment  node-name,  next,  previous,  up
@chapter Contributed Modules

SBCL comes with a number of modules that are not part of the core
system.  These are loaded via @code{(require :@var{modulename})}
(@pxref{Customization Hooks for Users}).  This section contains
documentation (or pointers to documentation) for some of the
contributed modules.

@menu
* sb-aclrepl::
* sb-concurrency::
* sb-cover::
* sb-grovel::
* sb-md5::
* sb-posix::
* sb-queue::
* sb-rotate-byte::
@end menu

@page
@include sb-aclrepl/sb-aclrepl.texinfo

@page
@include sb-concurrency/sb-concurrency.texinfo

@page
@include sb-cover/sb-cover.texinfo

@page
@include sb-grovel/sb-grovel.texinfo

@page
@include sb-md5/sb-md5.texinfo

@page
@include sb-posix/sb-posix.texinfo

@page
@include sb-queue/sb-queue.texinfo

@page
@include sb-rotate-byte/sb-rotate-byte.texinfo


