@node Profiling
@comment  node-name,  next,  previous,  up
@chapter Profiling
@cindex Profiling

SBCL includes both a deterministic profiler, that can collect statistics
on individual functions, and a more ``modern'' statistical profiler.

Inlined functions do not appear in the results reported by either.

@menu
* Deterministic Profiler::
* Statistical Profiler::
@end menu

@node Deterministic Profiler
@comment  node-name,  next,  previous,  up
@section Deterministic Profiler
@cindex Profiling, deterministic

The package @code{sb-profile} provides a classic, per-function-call
profiler.

@quotation note
When profiling code executed by multiple threads in parallel, the
consing attributed to each function is inaccurate.
@end quotation

@include macro-sb-profile-profile.texinfo
@include macro-sb-profile-unprofile.texinfo
@include fun-sb-profile-report.texinfo
@include fun-sb-profile-reset.texinfo

@node Statistical Profiler
@comment  node-name,  next,  previous,  up
@section Statistical Profiler
@include sb-sprof/sb-sprof.texinfo
