\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename sbcl.info
@settitle SBCL User Manual
@c %**end of header


@include variables.texinfo
@set EDITION 0.1
@settitle SBCL @value{VERSION} User Manual 

@c for install-info
@dircategory Software development
@direntry
* sbcl: (sbcl).           The Steel Bank Common Lisp compiler
@end direntry

@copying

@quotation
This manual is part of the SBCL software system. See the
@file{README} file for more information.

This manual is largely derived from the manual for the CMUCL system,
which was produced at Carnegie Mellon University and later released
into the public domain. This manual is in the public domain and is
provided with absolutely no warranty. See the @file{COPYING} and
@file{CREDITS} files for more information.
@end quotation

@end copying

@titlepage

@title SBCL User Manual
@subtitle SBCL version @value{VERSION}
@subtitle @value{UPDATE-MONTH}
@c @author The CMUCL and SBCL teams


@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

@end titlepage

@contents

@ifnottex

@node Top
@comment  node-name,  next,  previous,  up
@top sbcl

@insertcopying

@menu
* Introduction::                
* Compiler::                    
* Debugger::                    
* Efficiency::                  
* Beyond the ANSI Standard::    
* Foreign Function Interface::  
* Extensible Streams::          
* Package Locks::               
* Networking::                  
* Profiling::                   
* Contributed Modules::         
* Concept Index::               
* Function Index::              
* Variable Index::              
* Type Index::                  
* Colophon::                    
@end menu

@end ifnottex

@node Introduction
@comment  node-name,  next,  previous,  up
@chapter Introduction
@include intro.texinfo

@node Compiler
@comment  node-name,  next,  previous,  up
@chapter Compiler
@include compiler.texinfo

@node Debugger
@comment  node-name,  next,  previous,  up
@chapter Debugger
@include debugger.texinfo

@node Efficiency
@comment  node-name,  next,  previous,  up
@chapter Efficiency
@include efficiency.texinfo

@node  Beyond the ANSI Standard
@comment  node-name,  next,  previous,  up
@chapter Beyond the ANSI Standard
@include beyond-ansi.texinfo

@node  Foreign Function Interface
@comment  node-name,  next,  previous,  up
@chapter Foreign Function Interface
@include ffi.texinfo

@node Extensible Streams
@comment  node-name,  next,  previous,  up
@chapter Extensible Streams
@include streams.texinfo

@node Package Locks
@comment  node-name,  next,  previous,  up
@chapter Package Locks
@include package-locks.texi-temp

@node Networking
@comment  node-name,  next,  previous,  up
@chapter Networking
@include sb-bsd-sockets/sb-bsd-sockets.texinfo

@node Profiling
@comment  node-name,  next,  previous,  up
@chapter Profiling
@include profiling.texinfo

@node Contributed Modules
@comment  node-name,  next,  previous,  up
@chapter Contributed Modules
@include contrib-modules.texinfo

@node Concept Index
@comment  node-name,  next,  previous,  up
@appendix Concept Index
@printindex cp

@node Function Index
@comment  node-name,  next,  previous,  up
@appendix Function Index
@printindex fn

@node Variable Index
@comment  node-name,  next,  previous,  up
@appendix Variable Index
@printindex vr

@node Type Index
@comment  node-name,  next,  previous,  up
@appendix Type Index
@printindex tp

@node Colophon
@comment  node-name,  next,  previous,  up
@unnumbered Colophon

This manual is maintained in Texinfo, and automatically translated
into other forms (e.g. HTML or pdf). If you're @emph{reading} this
manual in one of these non-Texinfo translated forms, that's fine, but
if you want to @emph{modify} this manual, you are strongly advised to
seek out a Texinfo version and modify that instead of modifying a
translated version. Even better might be to seek out @emph{the}
Texinfo version (maintained at the time of this writing as part of the
SBCL project at @uref{http://sbcl.sourceforge.net/}) and submit a
patch.


@bye
