\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename sbcl-internals.info
@settitle SBCL Internals
@c %**end of header

@settitle SBCL Internals

@c for install-info
@dircategory Software development
@direntry
* sbcl-internals: (sbcl-internals).   SBCL internal documentation
@end direntry

@copying
@quotation
This manual is part of the SBCL software system. See the
@file{README} file for more information.

This manual is in the public domain and is provided with absolutely no
warranty. See the @file{COPYING} and @file{CREDITS} files for more
information.
@end quotation
@end copying

@titlepage

@title SBCL Internals
@c @author The CMUCL and SBCL teams

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

@end titlepage

@contents

@ifnottex

@node Top
@comment  node-name,  next,  previous,  up
@top SBCL Internals

@insertcopying

@include top-menu.include

@end ifnottex

@include top-include.include

@bye
